src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <label>AccountId</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <label>TotalPrice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalProductCount__c</fullName>
        <label>TotalProductCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>OP-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderItem__c.object
<CustomObject>
    <fields>
        <fullName>OrderId__c</fullName>
        <label>OrderId</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>OrderItems</relationshipLabel>
        <relationshipName>OrderItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProductId__c</fullName>
        <label>ProductId</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>OrderItems</relationshipLabel>
        <relationshipName>OrderItems</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>OrderItem</label>
    <nameField>
        <displayFormat>OI-{00000}</displayFormat>
        <label>OrderItemId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OrderItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Featured Electronics</fullName>
                </value>
                <value>
                    <fullName>Smart Home</fullName>
                </value>
                <value>
                    <fullName>TV, Audio &amp; Home Theater</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Laptops</fullName>
                </value>
                <value>
                    <fullName>Desktops</fullName>
                </value>
                <value>
                    <fullName>Monitors</fullName>
                </value>
                <value>
                    <fullName>TVs</fullName>
                </value>
                <value>
                    <fullName>Projectors</fullName>
                </value>
                <value>
                    <fullName>Printers</fullName>
                </value>
                <value>
                    <fullName>Headphones</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OrderTriggerTest.cls
@isTest
public with sharing class OrderTriggerTest {
    @testSetup static void setup() {
        Account a = new Account(Name = 'Company Internal');
        insert a;  
        
        List<Product__c> listProducts = new List<Product__c>();
        for(Integer i = 0; i < 50; i++){
             listProducts.add(new Product__c(
                Name = 'Test' + i,
                Price__c = i,
                Family__c = 'Featured Electronics',
                Type__c = 'Laptops'
            ));
        }
       insert listProducts;          
    }

    @isTest
    static void TriggerTest(){
        Account acc = [SELECT Id FROM Account LIMIT 1];
        Order__c order = new Order__c( AccountId__c = acc.Id);
        insert order;
        List<Product__c> listItems = [SELECT Id, Price__c FROM Product__c]; 
        List<OrderItem__c> items = new List<OrderItem__c>();
        Decimal sumPrice = 0;
        Integer sumQuantity = 0;
        for(Product__c item : listItems){
            items.add(new OrderItem__c(
                OrderId__c = order.Id,
                ProductId__c = item.Id,
                Quantity__c = 1,
                Price__c = item.Price__c
            ));
            sumPrice += item.Price__c;
            sumQuantity += 1; 
        }                        
        insert items;
        order = [SELECT TotalPrice__c, TotalProductCount__c FROM Order__c];
        System.assertEquals(order.TotalPrice__c, sumPrice);
        System.assertEquals(order.TotalProductCount__c, sumQuantity);
    }    
}