src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <label>AccountId</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>OP-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderItem__c.object
<CustomObject>
    <fields>
        <fullName>OrderId__c</fullName>
        <label>OrderId</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>OrderItems</relationshipLabel>
        <relationshipName>OrderItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProductId__c</fullName>
        <label>ProductId</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>OrderItems</relationshipLabel>
        <relationshipName>OrderItems</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>OrderItem</label>
    <nameField>
        <displayFormat>OI-{00000}</displayFormat>
        <label>OrderItemId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OrderItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Featured Electronics</fullName>
                </value>
                <value>
                    <fullName>Smart Home</fullName>
                </value>
                <value>
                    <fullName>TV, Audio &amp; Home Theater</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <label>Image</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Laptops</fullName>
                </value>
                <value>
                    <fullName>Desktops</fullName>
                </value>
                <value>
                    <fullName>Monitors</fullName>
                </value>
                <value>
                    <fullName>TVs</fullName>
                </value>
                <value>
                    <fullName>Projectors</fullName>
                </value>
                <value>
                    <fullName>Printers</fullName>
                </value>
                <value>
                    <fullName>Headphones</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OrderCtrl.cls
public with sharing class OrderCtrl {
    
    @AuraEnabled
    public static Account getAccount(String recorId){
        if(!String.isBlank(recorId)){
            Account acc = [SELECT Name, AccountNumber 
                           FROM Account
                           WHERE Id = :recorId
                           LIMIT 10000];
            return acc;                            
        } else {
            return null;
        }
    }

    @AuraEnabled
    public static Boolean checkUserIsManager(){
        User u = [SELECT Id, IsManager__c, Firstname 
                  FROM User 
                  WHERE id = :userinfo.getuserid()];
        return u.IsManager__c;                  
    }

    @AuraEnabled
    public static Map<String, List<picklistWrapper>> getFilterData(){
        Map<String,String> mapField = new Map<String,String>();
        mapField.put('Type','Type__c');
        mapField.put('Family','Family__c');
        Map<String, List<picklistWrapper>> mapPicklist = new Map<String, List<picklistWrapper>>();
        for(String key : mapField.keySet()){
            List<picklistWrapper> listType = findPicklistOptions('Product__c', mapField.get(key));
            mapPicklist.put(key,listType);
        }
        return mapPicklist;
    }

    @AuraEnabled
    public static List<picklistWrapper> findPicklistOptions(String objAPIName, String fieldAPIname) {
        System.debug(objAPIName + ' --- '+fieldAPIname);
        List<picklistWrapper> returnValue = new list<picklistWrapper>();
		Map<String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
		Schema.sObjectType objType = schemaMap.get(objAPIName);
		Schema.DescribeSObjectResult objDescribe = objType.getDescribe();
		Map<String, Schema.SObjectField> fieldMap = objDescribe.fields.getMap();
		list <Schema.PicklistEntry> values = fieldMap.get(fieldAPIname).getDescribe().getPickListValues();
		for (Schema.PicklistEntry a: values) {
			picklistWrapper picklist = new picklistWrapper();
			picklist.label = a.getLabel();
			picklist.value = a.getValue();
			returnValue.add(picklist);            
		}
        return returnValue;
    }   
    
    @AuraEnabled
    public static void deleteDocument(String idDocument){
        System.debug('idDocument = ' + idDocument);
        if(!String.isBlank(idDocument)){
            ContentDocument[] doc = [SELECT Id 
                                    FROM ContentDocument 
                                    WHERE Id = :idDocument];
            if (doc.size() > 0){
                delete doc;
            }                        
        }
    }

    @AuraEnabled
    public static  List<Product__c> getListProduct(){
        List<Product__c> listProduct = [SELECT Id, Name, Price__c, Family__c,Image__c, Type__c, Description__c
                                        FROM Product__c
                                        LIMIT 10000];
        return listProduct;
    }

    @AuraEnabled
    public static String getContentVersion(String documentId){
        ContentVersion conV = [SELECT Id
                               FROM ContentVersion 
                               WHERE ContentDocumentId  = :documentId];
        return conV.Id;
    } 
    
    @AuraEnabled
    public static List<Product__c> searchProducts(String searchKey){
        String query = 'SELECT Id, Name, Price__c, Family__c,Image__c, Type__c, Description__c'+
                        ' FROM Product__c ';
        if(!String.isBlank(searchKey)){
            query+= ' WHERE Name like \'%'+searchKey+'%\'';
        }
               
        List<Product__c> listProducts = Database.query(query);               
        return listProducts;
    } 
    
    @AuraEnabled
    public static void createOrder(String listProductsJSON, String idAccount){
        if(!String.isBlank(listProductsJSON)&&(!String.isBlank(idAccount))){
            Order__c order = new Order__c( AccountId__c = idAccount);
            insert order;

            List<OrderItem__c> items = new List<OrderItem__c>();
            List<WrapperItemProduct> listItems = (List<WrapperItemProduct>) JSON.deserialize(listProductsJSON, List<WrapperItemProduct>.class);
            for(WrapperItemProduct product : listItems){
                items.add(new OrderItem__c(
                    OrderId__c = order.Id,
                    ProductId__c = product.productId,
                    Quantity__c = product.quantity,
                    Price__c = product.price
                ));
            }
            insert items;
        }
    }

    public class WrapperItemProduct{
        public String productId;
        public Integer quantity;
        public Decimal price;
    }

    public class picklistWrapper{
        @AuraEnabled 
		public string label;
        @AuraEnabled 
		public string value;
    }

}