src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <label>TotalPrice</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalProductCount__c</fullName>
        <label>TotalProductCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>OP-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderItem__c.object
<CustomObject>
    <fields>
        <fullName>OrderId__c</fullName>
        <label>OrderId</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>OrderItems</relationshipLabel>
        <relationshipName>OrderItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>OrderItem</label>
    <nameField>
        <displayFormat>OI-{00000}</displayFormat>
        <label>OrderItemId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OrderItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OrderTotalTriggerHandler.cls
public with sharing class OrderTotalTriggerHandler {
    
    public static void onAfterInsert(List<OrderItem__c> listItems) {
        System.debug(listItems);
        Set<Id> seIdOrder = new Set<Id>();
        for(OrderItem__c item : listItems){
            seIdOrder.add(item.OrderId__c);
        }
        Map<String,Map<String,Decimal>> mapOrders = new Map<String,Map<String,Decimal>>();
        
        for(Id orderId : seIdOrder){
            Decimal totalQuantity = 0;
            Decimal totalPrice = 0;
            Map<String, Decimal> mapTotal = new Map<String, Decimal>();
            for(OrderItem__c item : listItems){
                if(orderId == item.OrderId__c){
                    totalQuantity += item.Quantity__c;
                    totalPrice += item.Price__c;
                }
            }
            mapTotal.put('totalQuantity',totalQuantity);
            mapTotal.put('totalPrice',totalPrice);
            mapOrders.put(orderId, mapTotal);
        }
        List<Order__c> lisOrders = [SELECT Id, TotalProductCount__c, TotalPrice__c 
                                    FROM Order__c
                                    WHERE Id IN :seIdOrder];
        System.debug('lisOrders ' + lisOrders);
        List<Order__c> newListOrders = new List<Order__c>();

        for(Order__c order : lisOrders){
            Map<String, Decimal> mapOrderItem = mapOrders.get(order.Id);
            order.TotalProductCount__c = mapOrderItem.get('totalQuantity');
            order.TotalPrice__c = mapOrderItem.get('totalPrice');
            newListOrders.add(order);
        }
        System.debug(newListOrders);
        update newListOrders;

    }
}